name: mustache_builder_example
version: 1.0.0
description: Example to build *.html files from *.mustache.html source.

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  build_runner: ^0.10.1
  build_web_compilers: ^0.4.2
  mustache_builder:
    path: ../
