name: mustache_builder
version: 0.0.1
author: Jonathan Rezende <jodi.exe@gmail.com>
description: A builder for parsing files with mustache.
homepage: https://github.com/jodinathan/mustache_builder

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  build: ^1.0.0
  yaml: ^2.1.15
  mustache: ^1.1.1

dev_dependencies:
  build_test: ^0.10.0
  test: ^1.5.0
